cmake_minimum_required(VERSION 3.24)
project(PhialLifetimeTrace VERSION 0.1.0 LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL")
set(BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(ENABLE_SKYRIM_SE OFF CACHE BOOL "" FORCE)
set(ENABLE_SKYRIM_AE ON CACHE BOOL "" FORCE)
set(ENABLE_SKYRIM_VR OFF CACHE BOOL "" FORCE)
add_subdirectory("${COMMONLIB_ROOT}" CommonLibSSE)
find_package(minhook CONFIG REQUIRED)
add_library(PhialLifetimeTrace SHARED src/main.cpp)
target_link_libraries(PhialLifetimeTrace PRIVATE CommonLibSSE::CommonLibSSE minhook::minhook)
target_compile_definitions(PhialLifetimeTrace PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
target_compile_options(PhialLifetimeTrace PRIVATE /utf-8 /W4)
