#pragma once
#include <string>
#include <cmath>

namespace phial {
    struct KeyChoice { int code; const char* name; };
    // DirectInput scan codes and SKSE InputMap mouse/gamepad offsets.
    inline constexpr KeyChoice keys[] = {
        { 55, "Numpad *" },
        { 71, "Numpad 7" },
        { 72, "Numpad 8" },
        { 73, "Numpad 9" },
        { 74, "Numpad -" },
        { 75, "Numpad 4" },
        { 76, "Numpad 5" },
        { 77, "Numpad 6" },
        { 78, "Numpad +" },
        { 79, "Numpad 1" },
        { 80, "Numpad 2" },
        { 81, "Numpad 3" },
        { 82, "Numpad 0" },
        { 83, "Numpad ." },
        { 156, "Numpad Enter" },
        { 181, "Numpad /" },
        { 59, "F1" },
        { 60, "F2" },
        { 61, "F3" },
        { 62, "F4" },
        { 63, "F5" },
        { 64, "F6" },
        { 65, "F7" },
        { 66, "F8" },
        { 67, "F9" },
        { 68, "F10" },
        { 87, "F11" },
        { 88, "F12" },
        { 1, "Escape" },
        { 2, "1" },
        { 3, "2" },
        { 4, "3" },
        { 5, "4" },
        { 6, "5" },
        { 7, "6" },
        { 8, "7" },
        { 9, "8" },
        { 10, "9" },
        { 11, "0" },
        { 12, "-" },
        { 13, "=" },
        { 14, "Backspace" },
        { 15, "Tab" },
        { 16, "Q" },
        { 17, "W" },
        { 18, "E" },
        { 19, "R" },
        { 20, "T" },
        { 21, "Y" },
        { 22, "U" },
        { 23, "I" },
        { 24, "O" },
        { 25, "P" },
        { 26, "[" },
        { 27, "]" },
        { 28, "Enter" },
        { 29, "Left Ctrl" },
        { 30, "A" },
        { 31, "S" },
        { 32, "D" },
        { 33, "F" },
        { 34, "G" },
        { 35, "H" },
        { 36, "J" },
        { 37, "K" },
        { 38, "L" },
        { 39, ";" },
        { 40, "'" },
        { 41, "Backtick / ~" },
        { 42, "Left Shift" },
        { 43, "Backslash" },
        { 44, "Z" },
        { 45, "X" },
        { 46, "C" },
        { 47, "V" },
        { 48, "B" },
        { 49, "N" },
        { 50, "M" },
        { 51, "," },
        { 52, "." },
        { 53, "/" },
        { 54, "Right Shift" },
        { 56, "Left Alt" },
        { 57, "Space" },
        { 58, "Caps Lock" },
        { 69, "Num Lock" },
        { 70, "Scroll Lock" },
        { 157, "Right Ctrl" },
        { 183, "Print Screen" },
        { 184, "Right Alt" },
        { 197, "Pause" },
        { 199, "Home" },
        { 200, "Up" },
        { 201, "Page Up" },
        { 203, "Left" },
        { 205, "Right" },
        { 207, "End" },
        { 208, "Down" },
        { 209, "Page Down" },
        { 210, "Insert" },
        { 211, "Delete" },
        { 219, "Left Windows" },
        { 220, "Right Windows" },
        { 256, "Mouse left" },
        { 257, "Mouse right" },
        { 258, "Mouse middle" },
        { 259, "Mouse button 4" },
        { 260, "Mouse button 5" },
        { 261, "Mouse button 6" },
        { 262, "Mouse button 7" },
        { 263, "Mouse button 8" },
        { 264, "Mouse wheel up" },
        { 265, "Mouse wheel down" },
        { 266, "Gamepad D-pad up" },
        { 267, "Gamepad D-pad down" },
        { 268, "Gamepad D-pad left" },
        { 269, "Gamepad D-pad right" },
        { 270, "Gamepad Start" },
        { 271, "Gamepad Back" },
        { 272, "Gamepad Left stick" },
        { 273, "Gamepad Right stick" },
        { 274, "Gamepad LB" },
        { 275, "Gamepad RB" },
        { 276, "Gamepad A" },
        { 277, "Gamepad B" },
        { 278, "Gamepad X" },
        { 279, "Gamepad Y" },
        { 280, "Gamepad LT" },
        { 281, "Gamepad RT" },
    };
    inline std::string keyName(float code)
    {
        if (!std::isfinite(code)) return "Unknown key";
        for (const auto& key : keys) if (code == key.code) return key.name;
        return "Key code " + std::to_string(code);
    }
}
